### PR TITLE
Update to reportlab 4

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

Update to reportlab 4

### Proposed changes

- Remove version restriction
- Document installation of C extensions

### Resolved issues

Fixes: #699

### CODE REVIEW

**Comment by timobrembeck** [comment]
@stefan6419846 do you think this will do?

**Comment by stefan6419846** [comment]
Apart from the fact that this will break *reportlab* 3 due to the requirements and enforce the (recommended, but not yet officially required) Cairo backend, it looks okay for me. To avoid this, we probably would have to utilize requirement extras groups, which I am not sure of how much additional maintenance effort this would introduce.

**Comment by timobrembeck** [comment]
> Apart from the fact that this will break _reportlab_ 3 due to the requirements and enforce the (recommended, but not yet officially required) Cairo backend, it looks okay for me. To avoid this, we probably would have to utilize requirement extras groups, which I am not sure of how much additional maintenance effort this would introduce.

Hmm yes, I agree that it's not ideal. But for now probably better than the previous restriction. At least people who rely on old versions of reportlab can just pin xhtml2pdf to an older version as well...
In the long term, we can evaluate the use of extra dependencies, probably after #692 has been merged...

**Comment by viniciusd** [comment]
I am still debugging it, so I am sharing in case someone else had the same issue with the new version, I have reportlab==4.0.7 and xhtml2pdf==0.2.12.

I am getting the exception:
```
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), dest=result, encoding='UTF-8')
  File xhtml2pdf/document.py, line 196, in pisaDocument
    doc.build(context.story)
  File reportlab/platypus/doctemplate.py, line 1082, in build
    self.handle_flowable(flowables)
  File reportlab/platypus/doctemplate.py, line 931, in handle_flowable
    if frame.add(f, canv, trySplit=self.allowSplitting):
  File reportlab/platypus/frames.py, line 169, in _add
    w, h = flowable.wrap(aW, h)
  File xhtml2pdf/xhtml2pdf_reportlab.py, line 832, in wrap
    remainingWidth -= colWidth
TypeError: unsupported operand type(s) for -=: 'float' and 'str'
```
I will do some digging before stating it is an issue/bug.

**Comment by viniciusd** [comment]
Yeah, it is a bug caused by a refactoring when the ruff linter was added:
https://github.com/xhtml2pdf/xhtml2pdf/commit/a3211b854672a09e257d8c4cf7192e30a2690d58#diff-74f01775643512741726dc5b4de3062a970be3ce0a07bd148192173000fb872dL822

I will create a separate issue for that.

**Pull request merged**
