### PR TITLE
Use GitHub Actions for Windows/Mac

### PR DESCRIPTION
**Pull request by captn3m0**
Attempting to move from AppVeyor for speed reasons.

### CODE REVIEW

**Comment by luisza** [comment]
Please consider don't remove coverage  for test.
Also see that Makefile exists so you can do

    make test
    make test-all

Make file is very important because helps in version  release.
Also I am working on remove all python2 code and using this Makefile to check code in local

**Comment by captn3m0** [comment]
Just removed `nose` mention from README. The CI tests are still running coverage, but they can't upload it to coveralls - could you add the `COVERALLS_TOKEN` to GitHub perhaps?

**Comment by luisza** [comment]
Hi, Sorry I have no permissions to get `COVERALLS_TOKEN` from coveralls.io that maybe @benjaoming can help.
Also coveralls.io is configured as Third-party application in the repository so token must be in the environment (I guest)

**Comment by luisza** [comment]
`arabic_font_rendering.html` test is failing because DejaVuSans.ttf not found, but can not be include on the repo for license limitations.

Also check `convert` behavior because time ago  test never ends because `convert` was waiting stdin infinite, maybe on CI is happen something like infinite waiting.

**Comment by benjaoming** [comment]
Hej :wave: 

I have just deleted the Coveralls.io repo -- I hope that you can create a new one in its place? It hadn't been active for 8 months. I did find a token but when I tried to add it here on Github in a secret environment, I found that other admins wouldn't be able to read it -- so it wasn't really the way to share it, I would just be the gatekeeper no matter what.

**Comment by luisza** [comment]
Consider test locally using https://github.com/nektos/act 
Also Linux support are required, I will work in Linux workflow also.

**Comment by benjaoming** [comment]
There is a great blog post by Hynek about simply not adding more CI for coverage reports:

https://hynek.me/articles/ditch-codecov-python/

**Comment by luisza** [comment]
@captn3m0 is there any update here ?  If not maybe i can work a little bit to help to add tests for windows and mac.

**Comment by luisza** [comment]
No more update here, so I will close this PR.

**Pull request closed without merging**
