### PR TITLE
Frame size bugfix

### PR DESCRIPTION
**Pull request by mawe42**
Ok, here's another pull request :-)

To illustrate the problem I was trying to fix, here's a test html page:
http://weseloh.cc/frame_test.html

Rendered with xhtml2pdf master branch results in this PDF:
http://weseloh.cc/frame_error.pdf

Using my frame-size-bugfix branch:
http://weseloh.cc/frame_correct.pdf

### CODE REVIEW

**Comment by drayendrff** [comment]
> nice :-) glad it finally worked.

@mawe42 can you elaborate on how to make it function cause I used a bootstrap 4.6.1 cdn and it doesnt trigger

**Comment by mawe42** [comment]
@drayendrff Sorry... but you are commenting an 11 year old(!) pull request and I don't understand your question.

**Comment by drayendrff** [comment]
@mawe42 i'm just trying to figure how to implement the boostrap into my PDFs, can you guide me thx

**Comment by mawe42** [comment]
No, sorry. A random and (11 year old!) PR ist definitely not the right place to ask. And I'm not the right person and your question is way too vague.

**Pull request merged**
