### PR TITLE
Add tests for base64 image

### PR DESCRIPTION
**Pull request by citizen-stig**
I only added a tests for #273 , but we could start work in this pull-request

### CODE REVIEW

**Comment by benjaoming** [comment]
Hello @citizen-stig thanks for writing tests for this issue! Would you be able to work on the resolution?

**Comment by citizen-stig** [comment]
Yes, I would!

**Comment by citizen-stig** [comment]
I've made a couple fixes and it works now

**Comment by benjaoming** [comment]
Thanks for this, will make sure it's released soon -- what's your assessment about the current state of things @citizen-stig ? Alpha or Beta?

**Comment by citizen-stig** [comment]
I think it's alpha, because it looks like example from documentation doesn't work on python2

**Pull request merged**
