### PR TITLE
Make cairo dependency optional

### PR DESCRIPTION
**Pull request by timobrembeck**
### Short description

Make cairo dependency optional

### Proposed changes

- Promote extra `xhtml2pdf[pycairo]` for `reportlab[pycairo]`

### Resolved issues

Fixes: #741

### CODE REVIEW

**Comment by timobrembeck** [comment]
@stefan6419846 What exactly do you mean? I didn't understand it completely, but to me it looks like `renderPM` is a rendering package (included in reportlab) which does not rely on system dependencies? So shouldn't it be possible to use this as default if `cairo` isn't installed?

**Comment by dwgreen1** [comment]
Is there any estimate on when this might be merged?

**Comment by timobrembeck** [comment]
@dwgreen1 I'm very sorry about the delay!

@stefan6419846 To be honest, I still don't understand all the implications of the render backend and how the library works if no backend is given.
If a rendering backend is always required, why is it possible to install reportlab without one?
Do you think this suggestion is fine to just propagate all available extras to reportlab and leave the decision which one to use to the end user?

**Comment by stefan6419846** [comment]
> To be honest, I still don't understand all the implications of the render backend and how the library works if no backend is given.

As linked above, *reportlab* will most likely fail to do anything useful if no render backend is set.

> If a rendering backend is always required, why is it possible to install reportlab without one?

I am clearly no *reportlab* expert and you should ask the developers about this. I can only guess that they want the user to actively decide on the corresponding backend. You can install *reportlab* without any extras if you happen to already have Cairo bindings in your requirements anyway for example.

The only relevant issue which arises here is for library authors depending on *reportlab* as *xhtml2pdf* does. It should (in my opinion) either propagate all relevant extras accordingly or do not require a specific extra, but tell the user in the installation/usage docs to install *reportlab* with the correct extras/backend.

> Do you think this suggestion is fine to just propagate all available extras to reportlab and leave the decision which one to use to the end user?

As mentioned in https://github.com/xhtml2pdf/xhtml2pdf/pull/742#issuecomment-1831772289 and in the previous paragraph, this would be the cleanest solution in my opinion. Nevertheless, this might need to be reflected in the changelog/usage docs as well due to requiring the *xhtml2pdf* user to actively decide on the rendering backend now.

**Comment by timobrembeck** [comment]
@stefan6419846 thanks for the clarification! Do you think now it's fine?

**Comment by stefan6419846** [comment]
Yes, LGTM.

**Comment by dwgreen1** [comment]
@timobrembeck This fixed my issue perfectly, thank you!

**Pull request merged**
