### PR TITLE
Master into develop

### PR DESCRIPTION
**Pull request by benjaoming**
@alistair-broomhead sorry didn't see that some of your work had gone into master. I'm going to add it to the develop branch now, hoping I'm not blowing up everything since it'll get mixed with the previous Python3 branch.

### CODE REVIEW

**Comment by alistair-broomhead** [comment]
Cheers, NP! Any chance you could mention me when you make your next release? Just so I can update our dependency from a tag on our github fork, to the pypi version ;)

**Comment by benjaoming** [comment]
@alistair-broomhead sure no problem at all -- would have done the gestures already, just it's a lot of work to get a contributors' list worked out, since the one already there is really outdated, but I'll have a look and see if we can start fiddling with something like that before releasing anything! Something is better than nothing!

**Comment by alistair-broomhead** [comment]
@benjaoming I'm not sure how much I can speak for others, but I'm not too bothered about appearing on the contributors list, if I were you I'd just make the contributors section a link to https://github.com/xhtml2pdf/xhtml2pdf/graphs/contributors and be done with it - software's a hard enough problem without managing an ever-changing list of who's credited, especially if there's already a system to do a passable job of it for you ;)

**Comment by benjaoming** [comment]
@alistair-broomhead not sure, I think it's to make the contributor's list a lasting part of the source code, as with LICENSE files etc? Not that I don't trust Github, but if someone decides to copy the source code, then then authors/contributors would remain... but the realistic part of me likes the suggestion :D

**Pull request merged**
