### PR TITLE
compatbility fix

### PR DESCRIPTION
**Pull request by sorter**
As html5lib has changed their structure this import needs to be updated for this project to continue to work.

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks @sorter -- but because of "legacy mode" of the project, #319 is probably favorable once it's updated to make tests work.

Are you willing to refactor the remaining codebase for these (not sure how many) changes to html5lib "internals"?

**Comment by Bakirelived** [comment]
so.. will the lib have an legacy code update or just the html5lib==1.0b8 requirements "fix"

**Comment by benjaoming** [comment]
Depends if anyone wants to do the actual code fix, I still favor the more "legacy-like" requirements fix.

**Comment by benjaoming** [comment]
This was fixed in #321 by pinning the htmllib version.

**Pull request closed without merging**
