### PR TITLE
That was wrong regexp for stripping up to an opening curly bracket, wasn't it?

### PR DESCRIPTION
**Pull request by o-pikozh**

### CODE REVIEW

**Comment by luisza** [comment]
Sorry, I don't see that your change work, could you please include in the description what cases doesn't work the actual regex ? 
So I can make tests for this expression if required but I see a good expression there.

**Comment by o-pikozh** [comment]
To say truth, I don't understand how the original regex (`.*({.*)`) was supposed to work at all. It just matches everything till the end of line. For example, for

    @media all and (max-width:768px){.builder {font-size:20px}
    ul.list_custom-icon {margin-top:-0.16em}
    }

(assuming that `@media all and ` is already read) it will match `(max-width:768px){.builder {font-size:20px}` (with `{.builder {font-size:20px}` as 1st capture group).

But `{` (not the LF) should be the criterion.

**Comment by o-pikozh** [comment]
BTW, my original sugesstion was also not 100% correct.

I originally suggested

    pattern = re.compile('.*?[{]')

but it should be

    pattern = re.compile('(?s:.)*?[{]')

or

    pattern = re.compile('.*?[{]', re.DOTALL)

**Comment by o-pikozh** [comment]
Are any additional details needed?

**Comment by luisza** [comment]
Implemented on 0.2.9.

**Comment by o-pikozh** [comment]
IMHO, [the addition described in the comment 1055672009](https://github.com/xhtml2pdf/xhtml2pdf/pull/598#issuecomment-1055672009) is still not implemented.

**Pull request closed without merging**
