### PR TITLE
Fix empty PDF in python2

### PR DESCRIPTION
**Pull request by citizen-stig**
Error was in the how CSS values have been processed.

In python 2 value if "display" style should be lowercased, but instead, only first letter has been set as value for this CSS property, os it was "display: b" in python2 instead of "display: block"

I don't know, why there's function lower, but as there's access by index to the sequence variable it should be list or tuple.  Maybe it's oversimplified, and we should check for subcalls, but at least it fixes the initial problem

### CODE REVIEW

**Comment by benjaoming** [comment]
Do you have suggestions regarding the PyPy failures? Some of the pypy testing is already skipped.

TBH, with the scope of the project, I can hardly see PyPy compatibility as a priority. With the skipped tests in mind, I would think it's probably already kind of broken.

**Comment by citizen-stig** [comment]
Unfortunately no, I don't, but I could try to investigate it.

I think, for now it's better to have support of python2 and python3 and when it works try to run on PyPy

**Comment by benjaoming** [comment]
Agreed, please feel free to comment it out in tox.ini! :)

**Comment by citizen-stig** [comment]
I disabled pypy in tox.ini and travis.yml and created issue https://github.com/xhtml2pdf/xhtml2pdf/issues/302 for that

**Comment by benjaoming** [comment]
Thanks a bunch, looks good!

**Pull request merged**
