### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by JimInCO**
I made some changes so that the tests now run in both Python 2 and and Python 3, [Build Status](https://travis-ci.org/JimInCO/xhtml2pdf). 
Most of the changes I made were the same as made by @wylee, in #205.

I also added a file to do Travis CI testing #202, and updated some of the dependencies.

### CODE REVIEW

**Comment by halfnibble** [comment]
These all look like solid code changes to me.

**Comment by xj9** [comment]
These changes are merged on [my branch][1].

[1]: https://github.com/zulumarketing/xhtml2pdf

**Comment by JimInCO** [comment]
Very cool. I'm not sure my pull request passes all of the functional tests in testrender. That should definitely be checked too.

**Comment by xj9** [comment]
Travis CI reports that all tests are passing.

**Comment by JimInCO** [comment]
I don’t think the test actually runs the functional tests (in the testrender folder). It seems that it only runs the unit tests (in tests folder).

**Comment by xj9** [comment]
There is an [issue in PyPDF2][1] preventing `testrender` from running successfully. Thankfully, there is also a [pull request][2] with a fix.

[1]: https://github.com/mstamy2/PyPDF2/issues/171
[2]: https://github.com/mstamy2/PyPDF2/pull/172

**Comment by benjaoming** [comment]
:+1: 

@chrisglass Python3 has to happen at some point :) This looks like a good effort and has Travis. If @JimInCO  adds in a Coverage report, you might be able to feel more or less encouraged to merge it.. but IMO the community should be lively enough to fix potential bugs introduced as long as you're willing to merge it.. I think adding Python3 is worth the risk of a little breakage.

**Comment by chrisglass** [comment]
Like I have mentioned many times before I have absolutely no interest in maintaining this project at all, so no merge is going to happen from me, ever.

If you think you can do a better job, I'll give you commit rights and a pat on the back.

**Comment by benjaoming** [comment]
@chrisglass - that's fair, I was aware that you were looking for someone to take over. Let me check with a friend who recently did a talk about xhtml2pdf :)

**Comment by benjaoming** [comment]
@chrisglass you're welcome to grant me rights, I'll put it on the agenda for the next [Django CPH](http://djangocph.dk) hackathon.

**Comment by ZuluPro** [comment]
@benjaoming: I've made this related PR #248

**Comment by michi88** [comment]
@benjaoming @ZuluPro same here https://github.com/xhtml2pdf/xhtml2pdf/pull/252 I would like to help  get this project to py3

**Comment by benjaoming** [comment]
@michi88 and @ZuluPro thanks! I'm here to assist in making sure good code is merged!!

Would someone be up for making a new PR with the contents of this and some kind of assessment of where things are and what's remaining?

**Comment by LegoStormtroopr** [comment]
Ok, so the latest travis run seems to suggest this runs under Py3.5. Is that the case?

**Comment by michi88** [comment]
@LegoStormtroopr Running testrender.py fails on numerous points. Needs work. So no.

**Comment by LegoStormtroopr** [comment]
So, I've forked the repo and have most of the python3 bugs ironed out. However, I have one small problem, and could use some input.

It seems that the only difference now is my outputs have a transparent background, and the test renders have a white background. There are lots of things that might be causing this, but I know for sure that its not report lab (I've checked it back a few versions in Python 2). So it must be a library.

Anyone got any clue on this?

**Comment by LegoStormtroopr** [comment]
I've got a new PR #260 that I'm actively working on, anyone with tips can jump in there.

**Comment by benjaoming** [comment]
This PR was forked by @LegoStormtroopr and his work in #260 is now merged in xhtml2pdf's 'python3' branch.

I'm going to rename the 'python3' branch to 'develop' and start doing pre-releases of 0.1.

**Pull request closed without merging**
